resolver: lts-6.7

packages:
- location:
    git: git@github.com:albertoruiz/hmatrix.git
    commit: 42a88fbcb6bd1d2c4dc18fae5e962bd34fb316a1
  subdirs:
    - packages/base
- .

extra-deps:
  - directory-1.2.7.0
  - text-1.2.2.1
  - stemmer-0.5.2
  - containers-0.5.7.1
  - Chart-1.8
  - Chart-cairo-1.8
